// packages/react/src/components/Tag.tsx
'use client'

import { ark, type HTMLArkProps } from '@ark-ui/react/factory'
import type { MouseEventHandler, PropsWithChildren } from 'react'
import { css, cx } from '@cerberus/styled-system/css'
import { tag, type TagVariantProps } from '@cerberus/styled-system/recipes'
import { useCerberusContext } from '../context/cerberus'
import { Show } from './Show'
import { IconButton } from './IconButton'

/**
 * This module contains the tag component.
 * @module
 */

export type StaticTagProps = HTMLArkProps<'span'> &
  TagVariantProps & {
    /**
     * The action to be performed when the tag is clicked. Not available when
     * the palette or gradient props are provided.
     */
    onClick?: never
  }

export type ClickableTagProps = HTMLArkProps<'span'> & {
  /**
   * The gradient to apply to the tag. Not available when the onClick prop is
   * provided.
   */
  gradient?: never
  /**
   * The palette to use for the tag. Not available when the onClick prop is
   * provided.
   */
  palette?: never
  /**
   * The action to be performed when the tag is clicked.
   */
  onClick: MouseEventHandler<HTMLSpanElement>
  /**
   * The shape of the tag. Not available when the onClick prop is provided.
   * @type 'pill' | 'rounded'
   * @default 'pill'
   */
  shape?: never
  /**
   * The usage of the tag. Not available when the onClick prop is provided.
   * @type 'filled' | 'outlined'
   * @default 'filled'
   */
  usage?: never
}

export type TagProps = StaticTagProps | ClickableTagProps

/**
 * The Tag component is used to display a meta descriptions.
 * @see https://cerberus.digitalu.design/react/tag
 * @example
 * ```tsx
 * <Tag>Tag</Tag>
 * ```
 */
export function Tag(props: PropsWithChildren<TagProps>) {
  const { shape: initShape, gradient, onClick, usage, ...nativeProps } = props
  const palette = props?.palette ?? 'page'
  const isClosable = Boolean(onClick)
  const shape = isClosable ? 'pill' : initShape
  const closableStyles = isClosable ? closableCss : ''
  const { icons } = useCerberusContext()
  const { close: Close } = icons

  return (
    <ark.span
      {...nativeProps}
      className={cx(
        nativeProps.className,
        tag({
          gradient,
          palette,
          shape,
          usage,
        }),
        closableStyles,
      )}
    >
      {props.children}

      <Show when={isClosable}>
        <IconButton
          ariaLabel="Close"
          onClick={onClick}
          palette="action"
          usage="filled"
          size="sm"
        >
          <Close />
        </IconButton>
      </Show>
    </ark.span>
  )
}

const closableCss = css({
  bgColor: 'action.bg.active',
  color: 'action.text.initial',
  paddingInlineEnd: '0',
})

// packages/solid/src/components/tag/tag.tsx
import { ark, type HTMLArkProps } from '@ark-ui/solid/factory'
import { splitProps, type ParentProps } from 'solid-js'
import { css, cx } from 'styled-system/css'
import { tag, type TagVariantProps } from 'styled-system/recipes'
import type { WithCss } from '../types'

/**
 * This module contains the tag component.
 * @module
 */

export type TagProps = HTMLArkProps<'span'> & TagVariantProps & WithCss

/**
 * The Tag component is used to display a meta descriptions.
 * @see https://cerberus.digitalu.design/components/tag
 * @example
 * ```tsx
 * <Tag>Tag</Tag>
 * ```
 */
export function Tag(props: ParentProps<TagProps>) {
  const [{ palette, shape, gradient, usage, css: customCss }, nativeProps] =
    splitProps(props, [
      'palette',
      'shape',
      'gradient',
      'onClick',
      'usage',
      'css',
    ])

  return (
    <ark.span
      {...nativeProps}
      class={cx(
        tag({
          gradient,
          palette,
          shape,
          usage,
        }),
        css(customCss),
        nativeProps.class,
      )}
    >
      {props.children}
    </ark.span>
  )
}
