// packages/react/src/components/admonition/parts.ts
import type { ElementType } from 'react'
import {
  AdmonitionContent,
  AdmonitionDescription,
  AdmonitionHeading,
  AdmonitionIndicator,
  AdmonitionRoot,
} from './primitives'

/**
 * This module contains the parts of the Admonition component.
 * @module 'admonition/parts'
 */

interface AdmonitionPartsValue {
  /**
   * The context provider of the Admonition.
   */
  Root: ElementType
  /**
   * The indicator of the Admonition.
   */
  Indicator: ElementType
  /**
   * The content of the Admonition.
   */
  Content: ElementType
  /**
   * The heading of the Admonition.
   */
  Heading: ElementType
  /**
   * The description of the Admonition.
   */
  Description: ElementType
}

/**
 * An Object containing the parts of the Accordion component. For users that
 * prefer Object component syntax.
 *
 * @remarks
 *
 * When using object component syntax, you import the AdmonitionParts object and
 * the entire family of components vs. only what you use.
 */
export const AdmonitionParts: AdmonitionPartsValue = {
  Root: AdmonitionRoot,
  Indicator: AdmonitionIndicator,
  Content: AdmonitionContent,
  Heading: AdmonitionHeading,
  Description: AdmonitionDescription,
}

// packages/solid/src/components/button/parts.ts
import type { JSX, ParentProps } from 'solid-js'
import { Button, type ButtonProps } from './button'
import { ButtonIcon } from './button-icon'

/**
 * This module contains the parts of the Button component.
 * @module 'button/parts'
 */

interface ButtonPartsValue {
  /**
   * The context provider of the button.
   */
  Root: (props: ButtonProps) => JSX.Element
  /**
   * The icon of the button.
   */
  Icon: (props: ParentProps) => JSX.Element
}

/**
 * An Object containing the parts of the Button component. For users that
 * prefer Object component syntax.
 *
 * @remarks
 *
 * When using object component syntax, you import the ButtonParts object and
 * the entire family of components vs. only what you use.
 */
export const ButtonParts: ButtonPartsValue = {
  Root: Button,
  Icon: ButtonIcon,
}
